### ISSUE TITLE
Add comparison to `monad-validate`

### ISSUE THREAD

**Issue by evanrelf** [kowainik/validation-selective#39]
It would be useful to compare `validation-selective` with Alexis King's [`monad-validate`](https://hackage.haskell.org/package/monad-validate) library.

**Comment by chshersh** [comment]
Hi @evanrelf, thanks for the suggestion. I'm a bit reluctant to compare with `monad-validate` since this package provides an entirely different interface. `monad-validate` provides a monadic interface for validation, based on transformers. `validation-selective` contains a simple sum type and builds interface around it. Even if both packages pursue similar goals, their implementations wholly different and in the _Comparison_ section we want to compare with same `Validation` types and other pure validation techniques. If you find any library for pure validation, we'll try to compare with it.

**Comment by evanrelf** [comment]
@chshersh I only brought it up since, if you ignore her `Validate` type's monad instance and don't use its transformer variant over `IO`, it's pretty similar.

If you still feel it still isn't similar enough to compare with that perspective, I understand 👍🏻
